name: Android Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.1'
      - name: Build APK
        run: gradle assembleRelease
        working-directory: android
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/*.apk
      - name: Release on GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: android/app/build/outputs/apk/release/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
